"devops":
  - ".github/**/*"
  - "Dockerfile"
  - "*entrypoint.sh"
"dependency":
  - "pyproject.toml"
  - "pdm.lock"
"documentation":
  - "docs/**/*"
  - "mkdocs.yml"
  - "README.md"
"version":
  - "osm_merge/__version__.py"
