name: 🔧 Build CI Img

on:
  # Push includes PR merge
  push:
    branches: [main]
    paths:
      # Workflow is triggered only if deps change
      - "pyproject.toml"
      - "Dockerfile"
  # Allow manual trigger
  workflow_dispatch:

jobs:
  ci-build:
    uses: hotosm/gh-workflows/.github/workflows/image_build.yml@1.2.4
    with:
      build_target: ci
      image_tags: |
        "ghcr.io/${{ github.repository }}:ci"
