name: Deploy Doxygen Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Doxygen Action
        uses: actions/checkout@v2
        with:
          doxyfile-path: ./docs/Doxyfile
          working-directory: docs

      - name: Deploy HTML
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html
          publish_branch: gh-pages
